# This is deployed manually, external-secrets on EKS would be better.
apiVersion: v1
kind: Secret
metadata:
  name: renovate
  namespace: renovate
type: Opaque
stringData:
  GITHUB_COM_TOKEN: "update me with base64 encoded value"
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_ENDPOINT: "https://github.company.com/api/v3"
  RENOVATE_GIT_AUTHOR: "Renovate Bot <bot@renovateapp.com>"
  RENOVATE_PLATFORM: "github"
  # RENOVATE_TOKEN: 'your-github-enterprise-renovate-user-token'
