# This is deployed manually, external-secrets on EKS would be better.
apiVersion: v1
kind: Secret
metadata:
  name: renovate
  namespace: renovate
type: Opaque
stringData:
  RENOVATE_TOKEN: ${GITHUB_TOKEN}
