apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate
  namespace: renovate
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  config.json: |-
    {
      "repositories": ["seanturner026/argocd-renovate"]
    }
