apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: renovate/renovate:35.38.0
              name: renovate
              env:
                - name: RENOVATE_GIT_AUTHOR
                  value: "Renovate Bot <bot@renovateapp.com>"
                - name: RENOVATE_PLATFORM
                  value: "github"
                - name: RENOVATE_AUTODISCOVER
                  value: "false"
                - name: RENOVATE_BASE_DIR
                  value: "/tmp/renovate/"
                - name: RENOVATE_CONFIG_FILE
                  value: "/opt/renovate/config.json"
                - name: LOG_LEVEL
                  value: INFO # DEBUG
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: RENOVATE_TOKEN
                      name: renovate
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate
            - name: work-volume
              emptyDir: {}
