apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seanturner026/argocd-renovate
    targetRevision: main
    path: applications
    directory:
      recurse: true
      include: 'application.yaml'
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
